server: 
  port: 1170

#按照注释部分填写配置，注意填写部分格式，冒号后面保留有一个空格
spring: 
  redis: 
    #redis（密码默认为空），请填写
    password: 
    #redis地址，默认127.0.0.1，请填写（需要注意本地redis和本地容器redis的host区别，本地默认127.0.0.1，docker默认redis）
    host: 
    #redis端口地址，默认6379
    port: 6379
  thymeleaf:
    content-type: text/html
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html

#青龙变量，请根据自己青龙地址填写
ql: 
  #青龙地址(直接填写ip或者域名，不带http和/)
  host: 
  #青龙端口
  port: 
  #青龙client_id
  client_id: 
  #青龙client_secret
  client_secret: 
